# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9'
  displayName: 'Install Python 3.9'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
    # Hier können weitere Build-Schritte hinzugefügt werden
  displayName: 'Install dependencies and build'


- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Marco'
    appName: 'app-service-albsig-dev'
    appType: 'webAppLinux'
    runtimeStack: 'PYTHON|3.9'
    package: '.'